version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: ex00_postgres
    environment:
      POSTGRES_USER: jedurand
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: piscineds
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
