version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: ex00_postgres
    environment:
      POSTGRES_USER: jedurand
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: piscineds
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: ex01_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: jedurand@42.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres

volumes:
  db_data:

# psql -U jedurand -d piscineds -h localhost -W